#####
#!/bin/sh
# ============================================================================
# Conformal LEC - Comprehensive Single File Script with Detailed Comments
# ============================================================================
# 
# Purpose: Perform logical equivalence checking between RTL (golden) and 
#          gate-level netlist (revised) designs
#
# Author: [Your Name]
# Date: [Date]
# Version: 1.0
#
# Usage: lec -nogui -dofile conformal_lec_detailed.tcl
#
# ============================================================================

# ============================================================================
# SECTION 1: VARIABLES AND CONFIGURATION
# ============================================================================
# This section defines all the variables used throughout the script.
# Centralizing variables makes the script easier to maintain and reuse.
# ============================================================================

# ----------------------------------------------------------------------------
# Design Information
# ----------------------------------------------------------------------------
# DESIGN_NAME: The name of your design/chip/block
#   - Used for naming output files and reports
#   - Should match your top-level module name (convention)
set DESIGN_NAME     "my_design"

# TOP_MODULE: The name of the top-level module in both RTL and netlist
#   - This is the module that will be set as the root for comparison
#   - Must be identical in both golden (RTL) and revised (netlist) designs
#   - Case-sensitive
set TOP_MODULE      "top"

# ----------------------------------------------------------------------------
# Directory Paths
# ----------------------------------------------------------------------------
# These paths define where all input files, libraries, and outputs are located
# Using absolute paths is recommended to avoid path resolution issues

# PROJECT_ROOT: Base directory for the entire project
#   - All other paths are typically relative to this
set PROJECT_ROOT    "/home/user/project"

# RTL_DIR: Location of RTL (Verilog/SystemVerilog) source files
#   - This is your "golden" or reference design
#   - Should contain behavioral/synthesizable RTL code
set RTL_DIR         "${PROJECT_ROOT}/rtl"

# NETLIST_DIR: Location of synthesized gate-level netlist
#   - This is your "revised" or implementation design
#   - Typically generated by synthesis tools (Genus, Design Compiler, etc.)
set NETLIST_DIR     "${PROJECT_ROOT}/synthesis/output"

# LIB_DIR: Location of technology library files
#   - Contains .lib (Liberty format) files for standard cells
#   - May also contain memory compiler libraries, IO pad libraries, etc.
set LIB_DIR         "${PROJECT_ROOT}/libs"

# WORK_DIR: Working directory for Conformal
#   - Used for temporary files during LEC run
#   - Session files are saved here
#   - Should have write permissions
set WORK_DIR        "${PROJECT_ROOT}/conformal/work"

# LOG_DIR: Directory for log files
#   - Contains detailed execution logs
#   - Useful for debugging script issues
set LOG_DIR         "${PROJECT_ROOT}/conformal/logs"

# REPORT_DIR: Directory for output reports
#   - Contains all verification reports
#   - Statistics, mapped/unmapped points, non-equivalences, etc.
set REPORT_DIR      "${PROJECT_ROOT}/conformal/reports"

# ----------------------------------------------------------------------------
# Library Files
# ----------------------------------------------------------------------------
# LIBERTY_LIBS: List of Liberty (.lib) format library files
#   - These define the functionality of standard cells used in the netlist
#   - Can include multiple libraries (multi-corner/multi-mode)
#   - Order doesn't typically matter, but cornermost libraries first is common
#   - Common library types:
#     * Standard cell libraries (slow, typical, fast corners)
#     * Memory libraries (SRAM, register files)
#     * IO pad libraries
#     * Analog/custom IP libraries
set LIBERTY_LIBS [list \
    "${LIB_DIR}/slow.lib" \
    "${LIB_DIR}/fast.lib" \
]
# Note: You can add more libraries as needed:
#   "${LIB_DIR}/memory.lib" \
#   "${LIB_DIR}/io_pads.lib" \

# ----------------------------------------------------------------------------
# Reference Design Files (RTL - Golden)
# ----------------------------------------------------------------------------
# REF_FILES: List of all RTL source files for the golden/reference design
#   - Order matters if there are dependencies between files
#   - Include all files that define modules used in your design
#   - Typically includes:
#     * Top-level module
#     * All sub-modules
#     * Utility modules
#     * Include files (if not using +incdir)
#   - Exclude:
#     * Testbench files
#     * Simulation-only files
#     * Files with `ifdef SYNTHESIS guards that shouldn't be synthesized
set REF_FILES [list \
    "${RTL_DIR}/top.v" \
    "${RTL_DIR}/ctrl_unit.v" \
    "${RTL_DIR}/datapath.v" \
    "${RTL_DIR}/alu.v" \
    "${RTL_DIR}/reg_file.v" \
]
# Tips:
#   - Use wildcards carefully: "${RTL_DIR}/*.v" might include unwanted files
#   - For large projects, consider generating this list automatically
#   - SystemVerilog files can be added with .sv extension

# ----------------------------------------------------------------------------
# Implementation Design Files (Gate-level Netlist - Revised)
# ----------------------------------------------------------------------------
# IMPL_FILES: List of synthesized gate-level netlist files
#   - Usually a single file, but can be multiple if netlist is hierarchical
#   - Generated by synthesis tools (Genus: write_hdl, DC: write -format verilog)
#   - Contains:
#     * Instantiations of standard cells from libraries
#     * Original module hierarchy (unless flattened during synthesis)
#     * Net names (may be optimized/renamed)
set IMPL_FILES [list \
    "${NETLIST_DIR}/${DESIGN_NAME}_netlist.v" \
]
# Note: If your synthesis tool outputs multiple netlist files:
#   "${NETLIST_DIR}/${DESIGN_NAME}_top.v" \
#   "${NETLIST_DIR}/${DESIGN_NAME}_subblock1.v" \
#   "${NETLIST_DIR}/${DESIGN_NAME}_subblock2.v" \

# ----------------------------------------------------------------------------
# Search Paths
# ----------------------------------------------------------------------------
# INCLUDE_DIRS: Directories to search for Verilog `include files
#   - Similar to -I flag in Verilog compilers
#   - Used when RTL has `include "header.vh" statements
#   - Common includes:
#     * Parameter definitions
#     * Macro definitions
#     * Interface definitions (SystemVerilog)
set INCLUDE_DIRS [list \
    "${RTL_DIR}/include" \
]
# Example include directory structure:
#   include/
#     ├── defines.vh       (global parameters)
#     ├── parameters.vh    (configuration parameters)
#     └── interfaces.svh   (SystemVerilog interfaces)

# ----------------------------------------------------------------------------
# Dofile Configuration
# ----------------------------------------------------------------------------
# DOFILE: Setup file generated during synthesis (optional but recommended)
#   - Similar to Formality's SVF (Setup Verification File)
#   - Contains information about synthesis optimizations
#   - Helps Conformal understand synthesis transformations
#   - Generated by synthesis tool:
#     * Genus: write_do_lec -golden_design rtl -revised_design netlist
#     * Design Compiler: set_svf command
#   - If not available, Conformal will rely on automatic inference
#   - Not having a dofile may result in:
#     * Longer runtime
#     * More unmapped points
#     * Potential false non-equivalences
set DOFILE          "${PROJECT_ROOT}/synthesis/${DESIGN_NAME}.do"

# ----------------------------------------------------------------------------
# Design Constraints
# ----------------------------------------------------------------------------
# These constraints help Conformal understand the operating conditions
# and improve comparison accuracy

# RESET_PINS: Reset signals and their inactive/active values
#   - Key: signal name (as it appears in design)
#   - Value: logic value during normal operation (typically 0 for active-low)
#   - Important because:
#     * Resets can cause different initialization values
#     * State machines may have different reset states in RTL vs netlist
#     * Sequential equivalence depends on reset conditions
#   - Syntax: signal_name value
#     * 0 = logic 0
#     * 1 = logic 1
#     * X = don't care (less common for resets)
array set RESET_PINS {
    rst_n       0
    arst_n      0
}
# Common reset signal names:
#   rst, reset, rst_n, reset_n (active low)
#   arst, async_reset (asynchronous reset)
#   srst, sync_reset (synchronous reset)

# CONST_PINS: Pins that are tied to constant values in your design
#   - Used for configuration, test modes, or unused inputs
#   - Key: signal name
#   - Value: constant logic value
#   - Examples:
#     * Test/scan signals (typically 0 during functional mode)
#     * Configuration selects
#     * Tie-offs for unused features
#   - Helps Conformal:
#     * Reduce comparison complexity
#     * Avoid false non-equivalences in unused logic paths
array set CONST_PINS {
    scan_en     0
    test_mode   0
}
# Additional examples you might add:
#   debug_mode   0
#   bist_mode    0
#   jtag_en      0
#   config_sel   2'b00  (can specify bus values)

# BLACK_BOXES: List of module names to treat as black boxes
#   - Black boxes are modules whose internal logic is not compared
#   - Only their inputs and outputs are checked for equivalence
#   - Use for:
#     * Third-party IP without source code
#     * Memory macros (SRAM, register files)
#     * Analog blocks
#     * Hard macros (PLLs, IOs, etc.)
#     * Modules verified separately
#   - Both golden and revised must have matching black boxes
set BLACK_BOXES [list \
]
# Examples to add:
#   "SRAM_128x32"     (memory compiler output)
#   "PLL_CORE"        (phase-locked loop)
#   "IO_PAD"          (IO pad cells)
#   "USB_PHY"         (analog PHY)
#   "AES_CRYPTO_IP"   (third-party IP)

# ----------------------------------------------------------------------------
# Verification Settings
# ----------------------------------------------------------------------------
# These settings control the effort and accuracy of the LEC run

# MODELING_EFFORT: Effort level for building internal models
#   - Options: "low", "medium", "high"
#   - Low: Faster, less accurate, good for quick checks
#   - Medium: Balanced speed and accuracy (recommended starting point)
#   - High: More thorough, slower, for complex designs
#   - Affects:
#     * How aggressively Conformal simplifies logic
#     * Time spent on model building
#   - Increase if you have:
#     * Complex combinational logic
#     * Large multiplexers or decoders
#     * Arithmetic operations
set MODELING_EFFORT     "medium"

# MAPPING_EFFORT: Effort level for mapping key points between designs
#   - Options: "low", "medium", "high"
#   - Mapping finds corresponding points (registers, ports) between golden/revised
#   - Low: Fast, relies on name matching
#   - Medium: Uses structural analysis + name matching
#   - High: Aggressive structural analysis, handles significant renaming
#   - Increase if:
#     * Many unmapped points reported
#     * Synthesis heavily renamed signals
#     * Hierarchies differ between RTL and netlist
set MAPPING_EFFORT      "medium"

# COMPARE_EFFORT: Effort level for equivalence comparison
#   - Options: "low", "medium", "high", "ultra"
#   - Controls how hard Conformal tries to prove equivalence
#   - Low: Fast, may give up on complex comparisons (more aborts)
#   - Medium: Good balance (recommended)
#   - High: Very thorough, much slower
#   - Ultra: Extreme effort, very slow, for difficult cases
#   - Increase if:
#     * Points marked as "aborted"
#     * Complex arithmetic or control logic
#     * Large state machines
set COMPARE_EFFORT      "medium"

# FLATTEN_MODEL: Controls logic flattening for comparison
#   - Options: "none", "seq", "comb", "all"
#   - "none": Maintain hierarchy (faster, recommended)
#   - "seq": Flatten through sequential elements
#   - "comb": Flatten combinational logic only
#   - "all": Flatten everything (slowest, most thorough)
#   - Flattening:
#     * Pros: Can resolve complex equivalences
#     * Cons: Much slower, uses more memory
#   - Use "none" initially, increase only if needed
set FLATTEN_MODEL       "none"

# MAX_RUNTIME: Maximum time in seconds for the entire verification
#   - Prevents runaway comparisons on very complex logic
#   - 3600 seconds = 1 hour (typical for medium designs)
#   - Increase for:
#     * Large designs (>500k gates)
#     * High effort settings
#     * Complex arithmetic/control logic
#   - Decrease for:
#     * Quick sanity checks
#     * Small design blocks
set MAX_RUNTIME         3600

# PARALLEL_CPUS: Number of CPU threads for parallel processing
#   - Conformal can use multiple threads for comparison
#   - Set to number of available CPU cores
#   - Typical values: 4, 8, 16
#   - More threads = faster runtime (with diminishing returns)
#   - Limited by:
#     * Available CPU cores on your machine
#     * Conformal license (some licenses limit parallelism)
#     * Memory (each thread uses memory)
set PARALLEL_CPUS       4

# ----------------------------------------------------------------------------
# Reporting Options
# ----------------------------------------------------------------------------

# GENERATE_HTML: Generate HTML format reports (in addition to text)
#   - 1 = enable, 0 = disable
#   - HTML reports are more readable and navigable
#   - Include:
#     * Hyperlinked statistics
#     * Color-coded results
#     * Easier to share with team
#   - Slightly slower to generate
set GENERATE_HTML       1

# VERBOSE_MODE: Enable verbose output and debugging
#   - 1 = enable, 0 = disable
#   - When enabled:
#     * More detailed console output
#     * Automatic diagnosis of first non-equivalent point
#     * Additional debug information in reports
#   - Useful for:
#     * Initial debug sessions
#     * Understanding failures
#   - Disable for:
#     * Regression testing
#     * Automated flows
set VERBOSE_MODE        1

# ============================================================================
# SECTION 2: INITIALIZATION
# ============================================================================
# This section initializes the Conformal environment and sets up logging
# ============================================================================

puts "============================================================================"
puts "Conformal LEC - Starting"
puts "Design: $DESIGN_NAME"
puts "Top Module: $TOP_MODULE"
puts "============================================================================\n"

# ----------------------------------------------------------------------------
# Create Output Directories
# ----------------------------------------------------------------------------
# Ensure all required output directories exist before starting
# This prevents errors when trying to write logs/reports
foreach dir [list $WORK_DIR $LOG_DIR $REPORT_DIR] {
    if {![file exists $dir]} {
        # file mkdir: TCL command to create directory
        #   - Creates parent directories if needed (like mkdir -p)
        #   - Returns error if creation fails (permissions, etc.)
        file mkdir $dir
        puts "Created directory: $dir"
    }
}

# ----------------------------------------------------------------------------
# Set Up Logging
# ----------------------------------------------------------------------------
# Create a timestamped log file for this run
# Timestamp format: YYYYMMDD_HHMMSS (e.g., 20240115_143022)
set timestamp [clock format [clock seconds] -format "%Y%m%d_%H%M%S"]

# LOG_FILE: Full path to the log file for this run
#   - Includes timestamp to avoid overwriting previous runs
#   - Contains all messages, commands, and results
set LOG_FILE "${LOG_DIR}/${DESIGN_NAME}_${timestamp}.log"

# set_log_file: Conformal command to redirect output to a log file
#   - All subsequent puts statements and Conformal messages go to this file
#   - -replace: Overwrite file if it exists (vs. -append to add to existing)
#   - Without this, messages only go to console
set_log_file $LOG_FILE -replace

puts "Log file: $LOG_FILE\n"

# ----------------------------------------------------------------------------
# Change to Working Directory
# ----------------------------------------------------------------------------
# cd: Change current directory to WORK_DIR
#   - All relative paths will be resolved from here
#   - Temporary files will be created here
#   - Session file will be saved here by default
cd $WORK_DIR

# ----------------------------------------------------------------------------
# Set System Mode
# ----------------------------------------------------------------------------
# set_system_mode: Conformal command to set the verification mode
#   - Options:
#     * lec: Logical Equivalence Checking (combinational + sequential)
#     * sec: Sequential Equivalence Checking (advanced, for retimed designs)
#     * setup: Setup mode (for advanced configuration)
#   - "lec" is the standard mode for RTL vs. netlist comparison
#   - This must be set before reading designs
set_system_mode lec

# ============================================================================
# SECTION 3: READ LIBRARIES
# ============================================================================
# Library files define the behavior of standard cells in the netlist
# Must be read before reading the gate-level netlist
# ============================================================================

puts "============================================================================"
puts "Reading Libraries"
puts "============================================================================"

# Loop through all Liberty library files
foreach lib $LIBERTY_LIBS {
    # Check if library file exists before attempting to read
    if {[file exists $lib]} {
        # read_library: Conformal command to read Liberty (.lib) files
        #   - Syntax: read_library <file> [-golden | -revised | -both]
        #   - -both: Make library available to both golden and revised designs
        #     * Common for RTL vs. netlist comparison
        #     * Library functions used in both (e.g., RAM models)
        #   - -golden: Only for golden design (rarely used)
        #   - -revised: Only for revised design (common for gate-level only libs)
        #   - Library defines:
        #     * Cell pin-to-pin logic functions
        #     * Timing information (not used in LEC)
        #     * Power information (not used in LEC)
        read_library $lib -both
        puts "✓ Loaded: $lib"
    } else {
        # If library doesn't exist, print error and exit
        #   - Missing libraries will cause netlist reading to fail
        #   - Better to fail early with clear error message
        puts "✗ ERROR: Library not found: $lib"
        exit 1
    }
}

puts ""

# ============================================================================
# SECTION 4: READ DESIGNS
# ============================================================================
# Read both the golden (RTL) and revised (netlist) designs
# Order: Read golden first, then revised (convention, not required)
# ============================================================================

# ----------------------------------------------------------------------------
# Read Golden Design (RTL/Reference)
# ----------------------------------------------------------------------------
puts "============================================================================"
puts "Reading Reference Design (Golden/RTL)"
puts "============================================================================"

# ----------------------------------------------------------------------------
# Add Include Search Paths
# ----------------------------------------------------------------------------
# add_search_path: Conformal command to add directories for `include resolution
#   - Similar to +incdir+ in Verilog compilers
#   - -design: Apply to design files (vs. -library for library files)
#   - Used when RTL contains: `include "header.vh"
#   - Without this, `include statements will fail
foreach path $INCLUDE_DIRS {
    if {[file exists $path]} {
        add_search_path $path -design
        puts "Added search path: $path"
    }
}

# ----------------------------------------------------------------------------
# Read RTL Files
# ----------------------------------------------------------------------------
foreach file $REF_FILES {
    # Check if file exists
    if {[file exists $file]} {
        # read_design: Conformal command to read design files
        #   - Syntax: read_design [-verilog | -vhdl | -edif] <file> [-golden | -revised]
        #   - -verilog: Specify Verilog/SystemVerilog format (auto-detected by extension)
        #   - -golden: Read as golden/reference design
        #   - Other options:
        #     * -vhdl: For VHDL designs
        #     * -edif: For EDIF format (uncommon)
        #     * -define: Add Verilog defines (like +define+)
        #     * -parameter: Override parameters
        #   - Conformal parses and elaborates the design
        #   - Multiple files are merged into a single design database
        read_design -verilog $file -golden
        puts "✓ Read: $file"
    } else {
        puts "✗ ERROR: File not found: $file"
        exit 1
    }
}

# ----------------------------------------------------------------------------
# Set Golden Top Module
# ----------------------------------------------------------------------------
# set_root_module: Conformal command to specify the top-level module
#   - Syntax: set_root_module <module_name> [-golden | -revised]
#   - Tells Conformal which module to use as the root for comparison
#   - Must be done after reading all design files
#   - Only ports and logic under this module will be compared
#   - Sub-modules are included automatically (unless black-boxed)
#   - Important:
#     * Module name must match exactly (case-sensitive)
#     * Module must be defined in one of the read files
#     * Can only set one top module per design
set_root_module $TOP_MODULE -golden
puts "Golden top module set: $TOP_MODULE\n"

# ----------------------------------------------------------------------------
# Read Revised Design (Gate-level Netlist)
# ----------------------------------------------------------------------------
puts "============================================================================"
puts "Reading Implementation Design (Revised/Netlist)"
puts "============================================================================"

# Read netlist files
#   - Similar to reading golden, but with -revised flag
#   - Netlist typically contains:
#     * Instances of standard cells (AND2X1, DFF, etc.)
#     * Original module hierarchy (unless flattened in synthesis)
#     * Potentially renamed signals/buses
#     * Optimized logic (constant propagation, don't-care optimization)
foreach file $IMPL_FILES {
    if {[file exists $file]} {
        read_design -verilog $file -revised
        puts "✓ Read: $file"
    } else {
        puts "✗ ERROR: File not found: $file"
        exit 1
    }
}

# Set revised top module
#   - Should be the same module name as golden
#   - If synthesis renamed the top module, use the new name here
set_root_module $TOP_MODULE -revised
puts "Revised top module set: $TOP_MODULE\n"

# ============================================================================
# SECTION 5: SETUP ENVIRONMENT
# ============================================================================
# Configure Conformal's behavior for this comparison
# These settings affect accuracy and runtime
# ============================================================================

puts "============================================================================"
puts "Setting Up Environment"
puts "============================================================================"

# ----------------------------------------------------------------------------
# Read Dofile (if available)
# ----------------------------------------------------------------------------
# read_dofile: Read a setup file from synthesis tool
#   - Contains synthesis-specific information:
#     * Constant propagation decisions
#     * Logic optimization choices
#     * FSM encoding changes
#     * Black box definitions
#     * Undriven/unloaded pin handling
#   - Helps Conformal understand what synthesis did
#   - Generated during synthesis:
#     * Genus: write_do_lec command
#     * DC: set_svf then write
#   - Without dofile, Conformal uses heuristics (less accurate)
if {[file exists $DOFILE]} {
    read_dofile $DOFILE
    puts "✓ Dofile loaded: $DOFILE"
} else {
    puts "⚠ Warning: Dofile not found: $DOFILE"
    puts "  Proceeding without dofile - may result in false negatives"
}

# ----------------------------------------------------------------------------
# Set Modeling Effort
# ----------------------------------------------------------------------------
# set_modeling_effort: Control how thoroughly Conformal builds internal models
#   - Syntax: set_modeling_effort [low | medium | high]
#   - Affects:
#     * BDD (Binary Decision Diagram) size limits
#     * SAT solver timeout
#     * Logic simplification aggressiveness
#   - Trade-off:
#     * Higher effort = more accurate but slower
#     * Lower effort = faster but may miss equivalences
#   - When to increase to "high":
#     * Many aborted comparisons
#     * Complex arithmetic (multipliers, dividers)
#     * Large state machines
set_modeling_effort $MODELING_EFFORT
puts "Modeling effort: $MODELING_EFFORT"

# ----------------------------------------------------------------------------
# Set Flatten Model
# ----------------------------------------------------------------------------
# set_flatten_model: Control logic flattening during comparison
#   - Syntax: set_flatten_model -seq_constant [none | seq | comb | all]
#   - -seq_constant: Flatten considering sequential constants
#   - Options:
#     * none: Preserve hierarchy (fastest, recommended)
#     * seq: Flatten sequential boundaries (registers)
#     * comb: Flatten combinational logic only
#     * all: Completely flatten (slowest, most thorough)
#   - Flattening can help with:
#     * Different hierarchy optimizations in synthesis
#     * Register retiming
#     * Complex equivalences across hierarchy
#   - Downsides:
#     * Much slower comparison
#     * Higher memory usage
#     * Less useful error messages (harder to debug)
set_flatten_model -seq_constant $FLATTEN_MODEL
puts "Flatten model: $FLATTEN_MODEL"

# ----------------------------------------------------------------------------
# Set Auto Mapping Effort
# ----------------------------------------------------------------------------
# set_mapping_effort: Control how hard to try mapping key points
#   - Syntax: set_mapping_effort [low | medium | high]
#   - Key points are:
#     * Primary inputs/outputs
#     * Flip-flops/latches
#     * Black box pins
#   - Mapping uses:
#     * Name matching (primary method)
#     * Structural analysis (when names differ)
#     * Functional analysis (expensive, high effort only)
#   - Increase to "high" if:
#     * Many unmapped points
#     * Synthesis significantly renamed signals
#     * Hierarchy differs between RTL and netlist
set_mapping_effort $MAPPING_EFFORT
puts "Mapping effort: $MAPPING_EFFORT"

# ----------------------------------------------------------------------------
# Enable Renaming Rules
# ----------------------------------------------------------------------------
# set_renaming_rules: Enable automatic signal name transformations
#   - Syntax: set_renaming_rules [-default | <custom_rules>]
#   - -default: Use Conformal's built-in renaming rules
#     * Handles common synthesis naming conventions
#     * Examples:
#       - _reg$ → (empty) : my_signal_reg → my_signal
#       - \[(\d+)\] → <\1> : bus[5] → bus<5>
#       - _n$ → (empty) : signal_n → signal (for inverted signals)
#   - Custom rules syntax: add_renaming_rule <pattern> <replacement> [-golden|-revised|-both]
#   - Helps map signals that synthesis renamed systematically
#   - Example custom rules:
#     add_renaming_rule {_r$} {} -revised     (remove _r suffix in netlist)
#     add_renaming_rule {_FF$} {_reg} -both   (map _FF to _reg)
set_renaming_rules -default
puts "Renaming rules enabled"

# ----------------------------------------------------------------------------
# Set Parallel Processing
# ----------------------------------------------------------------------------
# set_parallel_option: Enable multi-threaded comparison
#   - Syntax: set_parallel_option -threads <number>
#   - Distributes comparison work across CPU cores
#   - Speedup:
#     * 4 threads: ~2-3x faster
#     * 8 threads: ~4-5x faster
#     * 16 threads: ~6-8x faster (diminishing returns)
#   - Limited by:
#     * Available CPU cores
#     * License restrictions (some allow only single thread)
#     * Memory (each thread needs memory)
#   - Set to 1 for debugging (easier to trace issues)
set_parallel_option -threads $PARALLEL_CPUS
puts "Parallel threads: $PARALLEL_CPUS\n"

# ============================================================================
# SECTION 6: APPLY CONSTRAINTS
# ============================================================================
# Constraints tell Conformal about the operating environment
# Critical for accurate comparison
# ============================================================================

puts "============================================================================"
puts "Applying Constraints"
puts "============================================================================"

# ----------------------------------------------------------------------------
# Apply Reset Constraints
# ----------------------------------------------------------------------------
# add_pin_constraints: Constrain pins to specific values
#   - Syntax: add_pin_constraints <value> <pin_pattern> [-golden | -revised | -both]
#   - <value>: Logic value (0, 1, X, or binary string like 2'b10)
#   - <pin_pattern>: Signal name or pattern (* wildcard supported)
#   - -both: Apply to both golden and revised (most common)
#   - Why needed:
#     * Different reset initialization in RTL vs. netlist
#     * Undefined states at power-up
#     * Reset might propagate differently in optimized netlist
#   - Effect:
#     * Conformal assumes these values during comparison
#     * Prevents false non-equivalences in reset logic
if {[array exists RESET_PINS]} {
    puts "Reset Constraints:"
    foreach {pin value} [array get RESET_PINS] {
        add_pin_constraints $value $pin -both
        puts "  $pin = $value"
    }
}

# ----------------------------------------------------------------------------
# Apply Constant Constraints
# ----------------------------------------------------------------------------
# Similar to reset constraints, but for configuration/test signals
#   - Useful for:
#     * Disabling test logic (scan, BIST)
#     * Setting configuration modes
#     * Tying off unused features
#   - Example: If scan_en=0, scan chains are disabled
#     * Reduces comparison complexity
#     * Avoids checking test-only logic paths
if {[array exists CONST_PINS]} {
    puts "Constant Constraints:"
    foreach {pin value} [array get CONST_PINS] {
        add_pin_constraints $value $pin -both
        puts "  $pin = $value"
    }
}

# ----------------------------------------------------------------------------
# Set Up Black Boxes
# ----------------------------------------------------------------------------
# add_black_box: Tell Conformal to not compare inside certain modules
#   - Syntax: add_black_box <module_name> [-golden | -revised | -both]
#   - -both: Most common, when same module exists in both designs
#   - Effect:
#     * Module is treated as a "black box"
#     * Only I/O equivalence is checked
#     * Internal logic is not compared
#   - Use cases:
#     * Third-party IP (no source code)
#     * Memory macros (functionally equivalent, structurally different)
#     * Analog blocks (not representable in digital LEC)
#     * Pre-verified blocks
#   - Caution:
#     * Assumes the black box is correct
#     * Won't catch bugs inside the black box
if {[llength $BLACK_BOXES] > 0} {
    puts "Black Box Modules:"
    foreach module $BLACK_BOXES {
        add_black_box $module -both
        puts "  $module"
    }
}

puts ""

# ============================================================================
# SECTION 7: MAPPING
# ============================================================================
# Mapping identifies corresponding points between golden and revised designs
# These "key points" are where equivalence is checked
# ============================================================================

puts "============================================================================"
puts "Mapping Key Points"
puts "============================================================================"

# ----------------------------------------------------------------------------
# Add Mapped Points
# ----------------------------------------------------------------------------
# add_mapped_points: Specify which points should be compared
#   - Syntax: add_mapped_points [-all | <specific_points>]
#   - -all: Automatically add all comparable points
#     * Primary inputs/outputs (top-level ports)
#     * All flip-flops/registers
#     * Black box I/Os
#   - Specific points: Can manually add specific signals
#     * Useful for partial verification
#     * Example: add_mapped_points {golden:/WORK/top/reg_a revised:/WORK/top/reg_a}
#   - Key points are the "comparison points"
#     * These are where equivalence is actually checked
#     * Combinational logic between key points is compared automatically
add_mapped_points -all

# ----------------------------------------------------------------------------
# Run Mapping
# ----------------------------------------------------------------------------
# map_key_points: Execute the mapping algorithm
#   - Finds correspondence between golden and revised key points
#   - Uses:
#     * Name matching (primary method)
#     * Structural matching (based on fanin/fanout)
#     * User-defined renaming rules
#   - Results in:
#     * Mapped points: Successfully matched
#     * Unmapped points: No correspondence found
#   - Unmapped points need investigation:
#     * Missing in one design?
#     * Optimized away by synthesis?
#     * Named differently?
puts "Running automatic mapping..."
map_key_points

# ----------------------------------------------------------------------------
# Report Mapping Status
# ----------------------------------------------------------------------------
# Check how many points were successfully mapped
#   - report_mapped_points: Show all successfully mapped points
#     * -summary: Brief overview (count only)
#     * -verbose: Detailed list of each mapped point
#   - report_unmapped_points: Show points that couldn't be mapped
#     * These need investigation before comparison
puts "\nMapping Statistics:"
report_mapped_points -summary
report_unmapped_points -summary

# ----------------------------------------------------------------------------
# Check for Unmapped Points
# ----------------------------------------------------------------------------
# get_unmapped_points: Get list of unmapped key points
#   - Syntax: get_unmapped_points [-golden | -revised]
#   - Returns list of point names that weren't mapped
#   - Unmapped points won't be compared (potential verification gap)
set unmapped_g [get_unmapped_points -golden]
set unmapped_r [get_unmapped_points -revised]
set total_unmapped [expr {[llength $unmapped_g] + [llength $unmapped_r]}]

if {$total_unmapped > 0} {
    puts "\n⚠ WARNING: $total_unmapped unmapped points found"
    puts "  Golden unmapped: [llength $unmapped_g]"
    puts "  Revised unmapped: [llength $unmapped_r]"
    puts "  Common causes:"
    puts "    - Signal renamed in synthesis"
    puts "    - Logic optimized away (constant propagation)"
    puts "    - Missing in one design"
    puts "    - Need custom renaming rules"
} else {
    puts "\n✓ All key points mapped successfully"
}

puts ""

# ============================================================================
# SECTION 8: COMPARISON
# ============================================================================
# The actual equivalence checking happens here
# Compares combinational logic between all mapped key points
# ============================================================================

puts "============================================================================"
puts "Running Equivalence Checking"
puts "============================================================================"

# ----------------------------------------------------------------------------
# Set Comparison Effort
# ----------------------------------------------------------------------------
# set_compare_effort: Control thoroughness of equivalence checking
#   - Syntax: set_compare_effort [low | medium | high | ultra]
#   - Affects:
#     * SAT solver timeout
#     * BDD node limits
#     * Proof strategies attempted
#   - Low:
#     * Fast, but may abort on hard problems
#     * Good for quick sanity checks
#   - Medium:
#     * Balanced, recommended starting point
#   - High:
#     * Very thorough, much slower
#     * For designs with known complex logic
#   - Ultra:
#     * Maximum effort, extremely slow
#     * Last resort for difficult equivalences
#   - Start with medium, increase only if needed
set_compare_effort $COMPARE_EFFORT
puts "Compare effort: $COMPARE_EFFORT"

# ----------------------------------------------------------------------------
# Set Runtime Limit
# ----------------------------------------------------------------------------
# set_time_limit: Maximum time for entire verification
#   - Syntax: set_time_limit <seconds>
#   - Prevents runaway comparisons
#   - Per-point timeout is separate (controlled by effort settings)
#   - If limit reached:
#     * Current comparison aborts
#     * Results for completed points are still valid
#     * May need to increase limit or effort
#   - Typical values:
#     * Small blocks: 300-600 seconds (5-10 min)
#     * Medium designs: 1800-3600 seconds (30-60 min)
#     * Large designs: 7200+ seconds (2+ hours)
set_time_limit $MAX_RUNTIME
puts "Time limit: $MAX_RUNTIME seconds\n"

# ----------------------------------------------------------------------------
# Run Comparison
# ----------------------------------------------------------------------------
# compare: Execute the equivalence checking algorithm
#   - This is the core LEC operation
#   - For each mapped key point:
#     1. Builds logic cone from inputs to that point
#     2. Compares golden vs. revised logic cones
#     3. Attempts to prove equivalence or find counterexample
#   - Uses:
#     * Binary Decision Diagrams (BDDs)
#     * SAT solving
#     * Structural hashing
#     * Simulation
#   - Results:
#     * Equivalent: Proven identical
#     * Non-equivalent: Counterexample found (different behavior)
#     * Aborted: Couldn't prove either way (timeout, resource limit)
#     * Not compared: Skipped (shouldn't happen with proper setup)
#   - Runtime varies widely based on:
#     * Design complexity
#     * Logic depth
#     * Effort settings
#     * Unmapped points
puts "Starting comparison...\n"
compare

# ============================================================================
# SECTION 9: CHECK RESULTS
# ============================================================================
# Analyze the comparison results and determine pass/fail
# ============================================================================

puts "\n============================================================================"
puts "Verification Results"
puts "============================================================================\n"

# ----------------------------------------------------------------------------
# Get Comparison Statistics
# ----------------------------------------------------------------------------
# get_compare_points: Retrieve lists of points by status
#   - Syntax: get_compare_points [-all | -equivalent | -non_equivalent | -aborted | -not_compared]
#   - Returns: List of point names matching the filter
#   - Categories:
#     * -all: All comparison points (total)
#     * -equivalent: Successfully proven equivalent ✓
#     * -non_equivalent: Proven different (bug or setup issue) ✗
#     * -aborted: Comparison timed out or hit resource limit ⚠
#     * -not_compared: Not checked (shouldn't happen) ⚠

# Get count of points in each category
set total_points    [llength [get_compare_points -all]]
set equivalent      [llength [get_compare_points -equivalent]]
set non_equivalent  [llength [get_compare_points -non_equivalent]]
set aborted         [llength [get_compare_points -aborted]]
set not_compared    [llength [get_compare_points -not_compared]]

# Display statistics
puts "Total Compare Points:     $total_points"
puts "Equivalent:               $equivalent"
puts "Non-Equivalent:           $non_equivalent"
puts "Aborted:                  $aborted"
puts "Not Compared:             $not_compared"
puts ""

# ----------------------------------------------------------------------------
# Determine Pass/Fail
# ----------------------------------------------------------------------------
# Verification passes ONLY if:
#   1. All points are equivalent (non_equivalent == 0)
#   2. No points aborted (aborted == 0)
#   3. All points were compared (not_compared == 0)
#
# Any non-zero count in non_equivalent, aborted, or not_compared = FAIL
set VERIFICATION_PASSED 0
if {$non_equivalent == 0 && $aborted == 0 && $not_compared == 0} {
    puts "============================================================================"
    puts "✓✓✓ VERIFICATION PASSED ✓✓✓"
    puts "============================================================================"
    puts "All comparison points proven equivalent"
    set VERIFICATION_PASSED 1
} else {
    puts "============================================================================"
    puts "✗✗✗ VERIFICATION FAILED ✗✗✗"
    puts "============================================================================"
    
    # Provide specific failure reasons
    if {$non_equivalent > 0} {
        puts "⚠ $non_equivalent non-equivalent points detected"
        puts "  → Indicates functional mismatch or incorrect constraints"
        puts "  → Check non_equivalent report for details"
    }
    if {$aborted > 0} {
        puts "⚠ $aborted aborted points detected"
        puts "  → Comparison timed out or hit complexity limit"
        puts "  → Try: increase effort, flatten specific modules, or add constraints"
    }
    if {$not_compared > 0} {
        puts "⚠ $not_compared points were not compared"
        puts "  → Indicates setup issue"
        puts "  → Check that all points were properly mapped"
    }
}

puts ""

# ============================================================================
# SECTION 10: GENERATE REPORTS
# ============================================================================
# Create comprehensive reports for analysis and documentation
# Reports are saved to REPORT_DIR with timestamp
# ============================================================================

puts "============================================================================"
puts "Generating Reports"
puts "============================================================================"

# Create report filename prefix
#   - Includes design name and timestamp for uniqueness
#   - Example: my_design_20240115_143022_statistics.rpt
set RPT_PREFIX "${REPORT_DIR}/${DESIGN_NAME}_${timestamp}"

# ----------------------------------------------------------------------------
# Statistics Report
# ----------------------------------------------------------------------------
# report_statistics: Overall verification statistics
#   - Contains:
#     * Total runtime
#     * Memory usage
#     * Number of key points by type (DFF, port, etc.)
#     * Comparison results summary
#     * Effort settings used
#   - Syntax: report_statistics > <file>
#     * > redirects output to file (vs. console)
report_statistics > ${RPT_PREFIX}_statistics.rpt
puts "✓ ${RPT_PREFIX}_statistics.rpt"

# ----------------------------------------------------------------------------
# Mapping Reports
# ----------------------------------------------------------------------------
# report_mapped_points: List of all successfully mapped points
#   - Shows:
#     * Golden point name
#     * Revised point name
#     * Point type (DFF, output, black box, etc.)
#   - Useful for:
#     * Verifying correct mapping
#     * Understanding design structure
report_mapped_points > ${RPT_PREFIX}_mapped.rpt
puts "✓ ${RPT_PREFIX}_mapped.rpt"

# report_unmapped_points: List of points that couldn't be mapped
#   - Shows:
#     * Point name
#     * Which side (golden or revised)
#     * Why it couldn't be mapped (if determinable)
#   - Action items:
#     * Investigate each unmapped point
#     * Add renaming rules if systematic naming difference
#     * Verify point exists in both designs
report_unmapped_points > ${RPT_PREFIX}_unmapped.rpt
puts "✓ ${RPT_PREFIX}_unmapped.rpt"

# ----------------------------------------------------------------------------
# Comparison Report
# ----------------------------------------------------------------------------
# report_compare_data: Detailed comparison results for each point
#   - Shows:
#     * Point name
#     * Comparison status (equivalent, non-equivalent, aborted)
#     * Runtime for that comparison
#     * Resource usage
#   - Useful for:
#     * Identifying which points took longest
#     * Prioritizing debug efforts
report_compare_data > ${RPT_PREFIX}_compare.rpt
puts "✓ ${RPT_PREFIX}_compare.rpt"

# ----------------------------------------------------------------------------
# Non-Equivalent Points Report (if any)
# ----------------------------------------------------------------------------
# Only generate if there are non-equivalent points
if {$non_equivalent > 0} {
    # report_non_equivalent: Detailed information about non-equivalent points
    #   - Shows:
    #     * Point names that differ
    #     * Potential causes
    #     * Logic cones involved
    #   - First step in debugging functional mismatches
    report_non_equivalent > ${RPT_PREFIX}_non_equivalent.rpt
    puts "✓ ${RPT_PREFIX}_non_equivalent.rpt"
    
    # report_diagnosis: Root cause analysis of non-equivalences
    #   - Syntax: report_diagnosis [-all | <specific_point>]
    #   - -all: Diagnose all non-equivalent points
    #   - Provides:
    #     * Suggested root cause
    #     * Simplified logic equations
    #     * Potential fixes
    #   - Can be very large for many failing points
    report_diagnosis -all > ${RPT_PREFIX}_diagnosis.rpt
    puts "✓ ${RPT_PREFIX}_diagnosis.rpt"
}

# ----------------------------------------------------------------------------
# Aborted Points Report (if any)
# ----------------------------------------------------------------------------
# Only generate if there are aborted points
if {$aborted > 0} {
    # report_aborted: Details about comparisons that timed out
    #   - Shows:
    #     * Which points aborted
    #     * How much time was spent
    #     * Complexity metrics
    #   - Helps decide:
    #     * Should effort be increased?
    #     * Should logic be flattened?
    #     * Are constraints missing?
    report_aborted > ${RPT_PREFIX}_aborted.rpt
    puts "✓ ${RPT_PREFIX}_aborted.rpt"
}

# ----------------------------------------------------------------------------
# HTML Report (if enabled)
# ----------------------------------------------------------------------------
# Generate user-friendly HTML report
if {$GENERATE_HTML} {
    # report_html: Create interactive HTML report
    #   - Features:
    #     * Hyperlinked navigation
    #     * Color-coded results
    #     * Expandable sections
    #     * Charts/graphs
    #   - Easier to browse than text reports
    #   - Can be shared with non-LEC experts
    report_html ${RPT_PREFIX}.html
    puts "✓ ${RPT_PREFIX}.html"
}

puts "\nAll reports generated in: $REPORT_DIR\n"

# ============================================================================
# SECTION 11: DEBUG (IF VERIFICATION FAILED)
# ============================================================================
# Provide detailed debug information when verification fails
# Helps identify root causes quickly
# ============================================================================

if {!$VERIFICATION_PASSED} {
    puts "============================================================================"
    puts "Debug Information"
    puts "============================================================================\n"
    
    # ------------------------------------------------------------------------
    # List Non-Equivalent Points
    # ------------------------------------------------------------------------
    # Show first few non-equivalent points for quick reference
    if {$non_equivalent > 0} {
        puts "Non-Equivalent Points:"
        puts "----------------------"
        set neq_points [get_compare_points -non_equivalent]
        set count 0
        foreach point $neq_points {
            incr count
            puts "  $count. $point"
            # Limit output to first 10 to avoid overwhelming console
            if {$count >= 10} {
                set remaining [expr {$non_equivalent - 10}]
                puts "  ... and $remaining more (see non_equivalent.rpt for full list)"
                break
            }
        }
        puts ""
        
        # Common causes of non-equivalences
        puts "Common Causes:"
        puts "  • Incorrect or missing constraints (resets, modes)"
        puts "  • Synthesis optimization bugs (rare)"
        puts "  • RTL vs. netlist functional mismatch (design bug)"
        puts "  • Missing dofile information"
        puts "  • Clock gating or power management differences"
        puts ""
    }
    
    # ------------------------------------------------------------------------
    # List Aborted Points
    # ------------------------------------------------------------------------
    # Show first few aborted points
    if {$aborted > 0} {
        puts "Aborted Points:"
        puts "---------------"
        set abort_points [get_compare_points -aborted]
        set count 0
        foreach point $abort_points {
            incr count
            puts "  $count. $point"
            if {$count >= 10} {
                set remaining [expr {$aborted - 10}]
                puts "  ... and $remaining more (see aborted.rpt for full list)"
                break
            }
        }
        puts ""
        
        # Common causes of aborts
        puts "Common Causes:"
        puts "  • Logic too complex for current effort setting"
        puts "  • Large arithmetic operations (multipliers, dividers)"
        puts "  • Deep combinational logic (long critical paths)"
        puts "  • Insufficient runtime limit"
        puts ""
        
        # Suggested fixes
        puts "Suggested Fixes:"
        puts "  • Increase compare_effort to 'high' or 'ultra'"
        puts "  • Increase MAX_RUNTIME"
        puts "  • Flatten specific complex modules"
        puts "  • Add more specific constraints"
        puts ""
    }
    
    # ------------------------------------------------------------------------
    # List Unmapped Points
    # ------------------------------------------------------------------------
    # Show first few unmapped points from each side
    if {$total_unmapped > 0} {
        puts "Unmapped Points:"
        puts "----------------"
        
        # Unmapped in golden
        if {[llength $unmapped_g] > 0} {
            puts "Golden (missing in revised or can't map):"
            set count 0
            foreach point $unmapped_g {
                incr count
                puts "  $count. $point"
                if {$count >= 5} {
                    set remaining [expr {[llength $unmapped_g] - 5}]
                    puts "  ... and $remaining more"
                    break
                }
            }
        }
        
        # Unmapped in revised
        if {[llength $unmapped_r] > 0} {
            puts "Revised (missing in golden or can't map):"
            set count 0
            foreach point $unmapped_r {
                incr count
                puts "  $count. $point"
                if {$count >= 5} {
                    set remaining [expr {[llength $unmapped_r] - 5}]
                    puts "  ... and $remaining more"
                    break
                }
            }
        }
        puts ""
        
        # Common causes of unmapped points
        puts "Common Causes:"
        puts "  • Signal renamed by synthesis (need renaming rules)"
        puts "  • Logic optimized away (constant propagation)"
        puts "  • Register merged or duplicated"
        puts "  • Hierarchy changes (flattening, re-structuring)"
        puts ""
        
        # Suggested fixes
        puts "Suggested Fixes:"
        puts "  • Add custom renaming rules: add_renaming_rule <pattern> <replacement>"
        puts "  • Increase mapping_effort to 'high'"
        puts "  • Check if logic was intentionally optimized away"
        puts "  • Verify all design files are read correctly"
        puts ""
    }
    
    # ------------------------------------------------------------------------
    # Debug Suggestions
    # ------------------------------------------------------------------------
    # Comprehensive list of debugging steps
    puts "Debug Suggestions:"
    puts "------------------"
    if {$non_equivalent > 0} {
        puts "For Non-Equivalent Points:"
        puts "  1. Review ${RPT_PREFIX}_non_equivalent.rpt for detailed differences"
        puts "  2. Check constraints - are all resets and modes set correctly?"
        puts "  3. Verify dofile was generated and loaded"
        puts "  4. Use 'diagnose <point>' command to analyze specific failures"
        puts "  5. Compare RTL simulation vs. netlist simulation with same testbench"
        puts "  6. Check for synthesis warnings about optimizations"
    }
    if {$aborted > 0} {
        puts "For Aborted Points:"
        puts "  7. Increase COMPARE_EFFORT to 'high' or 'ultra'"
        puts "  8. Increase MAX_RUNTIME (current: $MAX_RUNTIME seconds)"
        puts "  9. Try flattening specific modules: set_flatten_model -module <name>"
        puts "  10. Add more constraints to simplify logic"
        puts "  11. Check for very wide arithmetic operations"
    }
    if {$total_unmapped > 0} {
        puts "For Unmapped Points:"
        puts "  12. Increase MAPPING_EFFORT to 'high'"
        puts "  13. Add custom renaming rules for systematic differences"
        puts "  14. Check synthesis logs for renamed/optimized signals"
        puts "  15. Verify both designs have the same top-level interface"
        puts "  16. Use 'report_naming_rules' to see current transformations"
    }
    puts ""
    
    # ------------------------------------------------------------------------
    # Analyze First Non-Equivalent Point (if verbose mode)
    # ------------------------------------------------------------------------
    # Automatically diagnose first failure for quick feedback
    if {$VERBOSE_MODE} {
        puts "============================================================================"
        puts "Analyzing First Non-Equivalent Point"
        puts "============================================================================\n"
        
        if {$non_equivalent > 0} {
            # Get first non-equivalent point
            set first_neq [lindex [get_compare_points -non_equivalent] 0]
            puts "Point: $first_neq\n"
            
            # diagnose: Conformal command to analyze a specific non-equivalence
            #   - Syntax: diagnose <point_name> [-verbose]
            #   - Provides:
            #     * Simplified boolean equations for golden vs. revised
            #     * Identified differences in logic
            #     * Suggested root causes
            #   - Very useful for understanding the first failure
            #   - Note: Can be slow for complex points
            puts "Running diagnosis (this may take a moment)...\n"
            catch {diagnose $first_neq} result
            puts $result
            puts ""
            puts "For more details, see: ${RPT_PREFIX}_diagnosis.rpt"
        }
    }
}

# ============================================================================
# SECTION 12: SAVE SESSION
# ============================================================================
# Save the Conformal session for later analysis
# Allows resuming the session without re-running the entire flow
# ============================================================================

puts "\n============================================================================"
puts "Saving Session"
puts "============================================================================"

# Create session filename with timestamp
set SESSION_FILE "${WORK_DIR}/${DESIGN_NAME}_${timestamp}.lec"

# write_session: Save current Conformal state to file
#   - Syntax: write_session <filename>
#   - Saves:
#     * All loaded designs
#     * Library information
#     * Mapping results
#     * Comparison results
#     * Settings and constraints
#   - Does NOT save:
#     * Intermediate computation data (BDDs, etc.)
#     * Open GUI windows
#   - Session can be loaded later with: read_session <filename>
#   - Use cases:
#     * Resume debugging without re-running comparison
#     * Share results with team
#     * Archive for documentation
#   - File format: Binary (.lec extension)
#   - Can be large (100s of MB for big designs)
write_session $SESSION_FILE
puts "✓ Session saved: $SESSION_FILE"
puts "  To resume: lec -gui
"
puts "             LEC> read_session $SESSION_FILE\n"

# ============================================================================
# SECTION 13: SUMMARY
# ============================================================================
# Final summary of the verification run
# Quick reference for key information and results
# ============================================================================

puts "============================================================================"
puts "Summary"
puts "============================================================================"
puts "Design:           $DESIGN_NAME"
puts "Top Module:       $TOP_MODULE"
puts "Status:           [expr {$VERIFICATION_PASSED ? "PASSED ✓" : "FAILED ✗"}]"
puts "Total Points:     $total_points"
puts "Equivalent:       $equivalent"
puts "Non-Equivalent:   $non_equivalent"
puts "Aborted:          $aborted"
puts "Unmapped:         $total_unmapped"
puts ""
puts "Files Generated:"
puts "  Log:            $LOG_FILE"
puts "  Reports:        $REPORT_DIR/${DESIGN_NAME}_${timestamp}_*.rpt"
puts "  Session:        $SESSION_FILE"
puts "============================================================================\n"

# Additional recommendations based on results
if {$VERIFICATION_PASSED} {
    puts "Next Steps:"
    puts "  • Review reports for any warnings"
    puts "  • Archive session file for records"
    puts "  • Proceed with physical design (P&R)"
    puts ""
} else {
    puts "Next Steps:"
    puts "  • Review debug information above"
    puts "  • Examine detailed reports in $REPORT_DIR"
    puts "  • Load session in GUI for interactive debug: lec -gui"
    puts "  • Contact design/verification team if issues persist"
    puts ""
}

# ============================================================================
# SECTION 14: EXIT WITH STATUS CODE
# ============================================================================
# Exit the script with appropriate return code
# Important for automation and regression flows
# ============================================================================

# exit: TCL command to terminate script
#   - Argument: Return code (0 = success, non-zero = failure)
#   - Return code can be checked by calling script/shell:
#     * Bash: $? variable
#     * Make: triggers rule failure on non-zero
#     * CI/CD: marks build as failed
#   - Convention:
#     * 0: Verification passed
#     * 1: Verification failed
#     * Other codes can indicate different failure types
if {$VERIFICATION_PASSED} {
    puts "Exiting with status 0 (SUCCESS)"
    exit 0
} else {
    puts "Exiting with status 1 (FAILURE)"
    exit 1
}

# ============================================================================
# END OF SCRIPT
# ============================================================================
